### ISSUE TITLE
release for 24.08 sdk?

### ISSUE THREAD

**Issue by vixalien** [flathub/org.freedesktop.Sdk.Extension.typescript#29]
depends on https://github.com/flathub/org.freedesktop.Sdk.Extension.node20/issues/17

**Comment by vixalien** [comment]
node freedesktop SDK has now been 24.08'd

**Comment by A6GibKm** [comment]
@vixalien does this require node20? Can it use node22?

**Comment by vixalien** [comment]
No, it does not require node20, but I thought node SDK Extensions were based on LTS versions, hence why node22 as a SDK Extension doesn't exist yet.

**Comment by A6GibKm** [comment]
Ok, I didn't count with that information (20 being LTS unlike 22), then it makes sense to use 20. Thanks!

**Comment by bilelmoussaoui** [comment]
should be there in a bit
